name: PhoneCheck
options:
  bundleIdPrefix: com.xq
targets:
  PhoneCheck:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - PhoneCheck
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xq.phonecheck
        MARKETING_VERSION: "1.3"
        CURRENT_PROJECT_VERSION: 4
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SUPPORTS_MACCATALYST: NO

schemes:
  PhoneCheck:
    build:
      targets:
        PhoneCheck: all
